### ISSUE TITLE
keystroke down key doesn't work after suggestions

### ISSUE THREAD

**Issue by mishal23** [krahulreddy/nominatim-indexing#1]
Hi, I tried this feature from this link: https://gsoc2020.nominatim.org/nominatim/ui/search.html, great work on the project and seems pretty useful! :)

But, would be great if after the suggestions are loaded, we can choose the location using the keyboard down arrow key, currently only the mouse input works.

**Comment by krahulreddy** [comment]
Thank you for the suggestion!

This has been fixed on the [suggestions branch](https://github.com/krahulreddy/nominatim-ui/tree/suggestions) of Nominatim UI. The changes are now accessible at https://gsoc2020.nominatim.org/nominatim/ui/search.html (Please note that this link might not be accessible after September 2020).

**Comment by mishal23** [comment]
Thanks, @krahulreddy for fixing this soon, looks good now 👍 , do let me know once it's deployed to production.
